src/AppBundle/Entity/Debt.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Debt
 *
 * @ORM\Table(name="debt")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\DebtRepository")
 */
class Debt
{

    const TYPE_LAB       = 0;
    const TYPE_PRACT_RAB = 1;
    const TYPE_ZACHET    = 2;
    const TYPE_EXAM      = 3;
    const TYPE_PRACTICE  = 4;

    //константы для типизации оценок
    const SINGLE = 0;
    const BUNDLE = 1;

    public static $types = [
        self::TYPE_LAB       => "Лабораторная",
        self::TYPE_PRACT_RAB => "Практическая",
        self::TYPE_ZACHET    => "Зачёт",
        self::TYPE_EXAM      => "Экзамен",
        self::TYPE_PRACTICE  => "Практика",
    ];

    public static $valueTypes = [
        self::TYPE_LAB       => self::BUNDLE,
        self::TYPE_PRACT_RAB => self::BUNDLE,
        self::TYPE_ZACHET    => self::SINGLE,
        self::TYPE_EXAM      => self::SINGLE,
        self::TYPE_PRACTICE  => self::SINGLE
    ];


    /**
     * @var int
     *
     * @ORM\Column(name="Dbt_Id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Subject", inversedBy="id")
     * @ORM\JoinColumn(name="Dbt_Sbj_Id", referencedColumnName="Sbj_Id")
     */
    private $subject;

    /**
     * @var
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\DebtValue", mappedBy="debt", cascade={"remove"})
     */
    private $values;

    /**
     * @var integer
     * @ORM\Column(name="Obt_Type", type="integer")
     */
    private $type;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set subject
     *
     * @param \AppBundle\Entity\Subject $subject
     *
     * @return Debt
     */
    public function setSubject(\AppBundle\Entity\Subject $subject = null)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get subject
     *
     * @return \AppBundle\Entity\Subject
     */
    public function getSubject()
    {
        return $this->subject;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->values = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add value
     *
     * @param \AppBundle\Entity\DebtValue $value
     *
     * @return Debt
     */
    public function addValue(\AppBundle\Entity\DebtValue $value)
    {
        $this->values[] = $value;

        return $this;
    }

    /**
     * Remove value
     *
     * @param \AppBundle\Entity\DebtValue $value
     */
    public function removeValue(\AppBundle\Entity\DebtValue $value)
    {
        $this->values->removeElement($value);
    }

    /**
     * Get values
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Set type
     *
     * @param integer $type
     *
     * @return Debt
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @return mixed
     */
    public function getTypeName()
    {
        return self::$types[$this->type];
    }

    /**
     * @return bool
     */
    public function isClosed()
    {
        /** @var DebtValue $value */
        foreach ($this->getValues() as $value){
            if($value->getValue() == 0){
                return false;
            }
        }
        return true;
    }

    /**
     * @return mixed
     */
    public function getValueType()
    {
        return self::$valueTypes[$this->type];
    }
}

src/AppBundle/Entity/Schedule.php
<?php

namespace AppBundle\Entity;

use CalendarBundle\Component\WeekConstant;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Schedule
 *
 * @ORM\Table(name="schedule")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ScheduleRepository")
 */
class Schedule
{
    /**
     * @var int
     *
     * @ORM\Column(name="Sch_Id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Subject", inversedBy="schedule")
     * @ORM\JoinColumn(name="Sch_Sbj_Id", referencedColumnName="Sbj_Id")
     */
    private $subject;

    /**
     * @var integer
     * @ORM\Column(name="Sch_Dow", type="integer")
     * @Assert\Range(
     *     min="0",
     *     max="5"
     *     )
     */
    private $dow;

    /**
     * @var integer
     * @ORM\Column(name="Sch_Week_Type", type="integer")
     * @Assert\Range(
     *     min="0",
     *     max="2"
     *     )
     */
    private $weekType;

    /**
     * @var integer
     * @ORM\Column(name="Sch_Number", type="integer")
     * @Assert\Range(
     *     min="1",
     *     max="8"
     *     )
     */
    private $number;


    /**
     * @var int
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="id")
     * @ORM\JoinColumn(name="Sch_Student_Id")
     */
    private $user;

    /**
     * @var string
     * @ORM\Column(name="Sch_Auditory", type="string")
     */
    private $auditory;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set subject
     *
     * @param \AppBundle\Entity\Subject $subject
     *
     * @return Schedule
     */
    public function setSubject(\AppBundle\Entity\Subject $subject = null)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get subject
     *
     * @return \AppBundle\Entity\Subject
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     *
     * @return Schedule
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set dow
     *
     * @param integer $dow
     *
     * @return Schedule
     */
    public function setDow($dow)
    {
        $this->dow = $dow;

        return $this;
    }

    /**
     * Get dow
     *
     * @return integer
     */
    public function getDow()
    {
        return $this->dow;
    }

    /**
     * Set weekType
     *
     * @param integer $weekType
     *
     * @return Schedule
     */
    public function setWeekType($weekType)
    {
        $this->weekType = $weekType;

        return $this;
    }

    /**
     * Get weekType
     *
     * @return integer
     */
    public function getWeekType()
    {
        return $this->weekType;
    }

    /**
     * Set number
     *
     * @param integer $number
     *
     * @return Schedule
     */
    public function setNumber($number)
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Get number
     *
     * @return integer
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * @return mixed
     */
    public function getDowName()
    {
        return WeekConstant::$daysOfWeek[$this->dow];
    }

    /**
     * @return string
     */
    public function getWeekTypeName()
    {
        if (array_key_exists($this->weekType, WeekConstant::$weekType)) {
            return WeekConstant::$weekType[$this->weekType];
        }

        return implode(", ", WeekConstant::$weekType);
    }


    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return Schedule
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set auditory
     *
     * @param string $auditory
     *
     * @return Schedule
     */
    public function setAuditory($auditory)
    {
        $this->auditory = $auditory;

        return $this;
    }

    /**
     * Get auditory
     *
     * @return string
     */
    public function getAuditory()
    {
        return $this->auditory;
    }
}

src/AppBundle/Entity/Teacher.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Teacher
 *
 * @ORM\Table(name="teacher")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TeacherRepository")
 */
class Teacher
{
    /**
     * @var int
     *
     * @ORM\Column(name="tch_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="tch_first", type="string", length=30)
     */
    private $first;

    /**
     * @ORM\Column(name="tch_last", type="string", length=30)
     */
    private $last;

    /**
     * @ORM\Column(name="tch_patronymic", type="string", length=30)
     */
    private $patronymic;


    /**
     * @var
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Subject", mappedBy="teacher", cascade={"persist", "remove"})
     */
    private $subjects;

    /**
     * @var int
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="id")
     * @ORM\JoinColumn(name="Tch_Student_Id")
     */
    private $user;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Teacher
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getFirst()
    {
        return $this->first;
    }

    /**
     * @param mixed $first
     * @return Teacher
     */
    public function setFirst($first)
    {
        $this->first = $first;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLast()
    {
        return $this->last;
    }

    /**
     * @param mixed $last
     * @return Teacher
     */
    public function setLast($last)
    {
        $this->last = $last;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPatronymic()
    {
        return $this->patronymic;
    }

    /**
     * @param mixed $patronymic
     * @return Teacher
     */
    public function setPatronymic($patronymic)
    {
        $this->patronymic = $patronymic;
        return $this;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->subjects = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add subject
     *
     * @param \AppBundle\Entity\Subject $subject
     *
     * @return Teacher
     */
    public function addSubject(\AppBundle\Entity\Subject $subject)
    {
        $this->subjects[] = $subject;

        return $this;
    }

    /**
     * Remove subject
     *
     * @param \AppBundle\Entity\Subject $subject
     */
    public function removeSubject(\AppBundle\Entity\Subject $subject)
    {
        $this->subjects->removeElement($subject);
    }

    /**
     * Get subjects
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubjects()
    {
        return $this->subjects;
    }

    public function getTeacherLabel()
    {
        return $this->last . " " . $this->first . " " . $this->patronymic;
    }

    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return Teacher
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }
}

src/AppBundle/Resources/views/form.html.twig
{{ form_start(form) }}
<div class="box-body">
    {{ form_row(form.last) }}
    {{ form_row(form.first) }}
    {{ form_row(form.patronymic) }}
</div>
<div class="box-footer">
    {{ form_row(form.save) }}

</div>
{{ form_end(form) }}

src/AppBundle/Resources/views/subject.html.twig
{% extends "base.html.twig" %}

{% block header_content %}
	{{ macros.page_header("Предмет", "") }}
{% endblock %}

{% block javascripts %}
	<script src="{{ asset("bundles/app/js/subject.js") }}"></script>
{% endblock %}

{% block admin_lte_breadcrumb %}
	{% if id is defined %}
		<div id="subject_id" data-id="{{ id }}"></div>
	{% endif %}
	<div class="row">
		<div class="col-sm-4">
			<div class="box box-primary subjectFormBox">
				<div class="box-header with-border">
					<h3 class="box-title">Предмет</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container"></div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>

		<div class="col-sm-4">
			<div class="box box-primary scheduleBox">
				<div class="box-header with-border">
					<h3 class="box-title">Расписание</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">
					<div class="box-body">
					</div>
					<div class="box-footer">
					</div>
				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="box box-primary scheduleListBox">
				<div class="box-header with-border">
					<h3 class="box-title">Список пар</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">
					<div class="box-body">
					</div>
					<div class="box-footer">
					</div>
				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-4">
			<div class="box box-primary debtFormBox">
				<div class="box-header with-border">
					<h3 class="box-title">Долги</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">
					<div class="box-body">
					</div>
					<div class="box-footer">
					</div>
				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="box box-primary debtListBox">
				<div class="box-header with-border">
					<h3 class="box-title">Открытые долги</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">

				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="box box-primary  closedDebtListBox">
				<div class="box-header with-border">
					<h3 class="box-title">Закрытые долги</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">

				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

src/AppBundle/Resources/views/subjectForm.html.twig
{{ form_start(form) }}
<div class="box-body">
	{{ form_row(form.name) }}
	{{ form_row(form.type) }}
	{{ form_row(form.teacher) }}
	{{ form_row(form.teacher_labs) }}
</div>
<div class="box-footer">
    {{ form_row(form.save) }}

</div>
{{ form_end(form) }}

src/AppBundle/Resources/views/subjectList.html.twig
<div class="teacher-list table-responsive">
	<table class="table table-bordered table-striped">
		<tr>
			<th>Номер</th>
			<th>Название</th>
			<th>Тип</th>
			<th>Преподаватель</th>
			<th></th>
		</tr>

		{% for subject in subjects %}
			<tr>
				<td><a href="{{ url('subject_form_id', {"id":subject.id }) }}">{{ subject.id  }}</a></td>
				<td>{{ subject.name }}</td>
				<td>{{ subject.typeName }}</td>
				<td>
					{% if subject.teacher is not null %}
						{{ subject.teacher.teacherLabel }}
					{% else %}
						-
					{% endif %}
				</td>
				<td><i class="fa fa-remove text-danger subject-remove" data-id="{{ subject.id }}"></i></td>
			</tr>
		{% else %}
			<tr>
				<td colspan="4" class="text-center">Нет предметов</td>
			</tr>
		{% endfor %}
	</table>
</div>

src/AppBundle/Resources/views/subjectListPage.html.twig
{% extends "base.html.twig" %}
{% block header_content %}
	{{ macros.page_header("", "") }}
{% endblock %}
{% block javascripts %}
	<script src="{{ asset("bundles/app/js/subjectList.js") }}"></script>
{% endblock %}

{% block label %}
	Список предметов
{% endblock %}

{% block admin_lte_breadcrumb %}

	<div class="row">

		<div class="col-sm-12">
			<div class="box box-primary subjectListBox">
				<div class="box-header with-border">
					<h3 class="box-title">Предметы</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">
					<div class="box-body">

					</div>
					<div class="box-footer">

					</div>
				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

src/AppBundle/Resources/views/subjectPreview.html.twig
<table class="table table-bordered table-stripped">
	<tr>
		<td><strong>Название</strong></td>
		<td>{{ subject.name }}</td>
	</tr>
	<tr>
		<td><strong>Преподаватель</strong></td>
		<td>{{ subject.teacher.teacherLabel }}</td>
	</tr>
	<tr>
		<td><strong>Тип</strong></td>
		<td>{{ subject.typeName }}</td>
	</tr>
	<tr>
		<td><strong>Расписание</strong></td>
		<td>
			<div class="teacher-list">
				<table class="table table-bordered table-striped">
					<tr>
						<th>Номер</th>
						<th>День недели</th>
						<th>Номер пары</th>
						<th>Тип недели</th>
					</tr>

					{% for sched in subject.schedule %}
						<tr>
							<td>{{ sched.id  }}</td>
							<td>{{ sched.dowName }}</td>
							<td>{{ sched.number }}</td>
							<td>{{ sched.weekTypeName }}</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="4" class="text-center">Нет в расписании</td>
						</tr>
					{% endfor %}
				</table>
			</div>
		</td>
	</tr>



</table>

src/AppBundle/Resources/views/subjectView.html.twig
<div class="box-body">
	<div class="row form-group">
		<div class="col-sm-6 text-right"><strong>Название</strong></div>
		<div class="col-sm-6">{{ subject.name }}</div>
	</div>
	<div class="row form-group">
		<div class="col-sm-6 text-right"><strong>Тип</strong></div>
		<div class="col-sm-6">
			{{ subject.typeName }},
			{% if subject.children is not null %}
				{{ subject.children.typeName }}
			{% endif %}
		</div>
	</div>
	<div class="row form-group">
		<div class="col-sm-6 text-right"><strong>Преподаватель</strong></div>
		<div class="col-sm-6">{{ subject.teacher.teacherLabel }}</div>
	</div>
	{% if subject.children is not null %}
		<div class="row form-group">
			<div class="col-sm-6 text-right"><strong>Преподаватель практических работ</strong></div>
			<div class="col-sm-6">{{ subject.children.teacher.teacherLabel }}</div>
		</div>
	{% endif %}
</div>
<div class="box-footer">
	<input type="button" class="btn btn-danger pull-right edit-subject" value="Изменить">
</div>

src/AppBundle/Resources/views/teacher.html.twig
{% extends "base.html.twig" %}
{% block header_content %}
	{{ macros.page_header("", "") }}
{% endblock %}
{% block javascripts %}
	<script src="{{ asset("bundles/app/js/teacher.js") }}"></script>
{% endblock %}

{% block admin_lte_breadcrumb %}
	{% if id is defined %}
		<div id="teacher_id" data-id="{{ id }}"></div>
	{% endif %}
	<div class="row">
		<div class="col-sm-4">
			<div class="box box-primary teacherFormBox">
				<div class="box-header with-border">
					<h3 class="box-title">Преподаватель</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container"></div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
		<div class="col-sm-8">
			<div class="box box-primary teacherListBox">
				<div class="box-header with-border">
					<h3 class="box-title">Предметы</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">
					<div class="box-body">

					</div>
					<div class="box-footer">

					</div>
				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>


			</div>
		</div>
	</div>


{% endblock %}

src/AppBundle/Resources/views/teacherList.html.twig
<div class="teacher-list table-responsive">
	<table class="table table-bordered table-striped">
		<tr>
			<th>Номер</th>
			<th>Фамилия</th>
			<th>Имя</th>
			<th>Отчество</th>
			<th></th>
		</tr>

		{% for teacher in teacherList %}
			<tr>

				<td><a href="{{ url('teacher_form_with_id', {"id": teacher.id}) }}">{{ teacher.id }}</a></td>
				<td>{{ teacher.last }}</td>
				<td>{{ teacher.first }}</td>
				<td>{{ teacher.patronymic }}</td>
				<td><i class="fa fa-remove text-danger teacher-remove" data-id="{{ teacher.id }}"></i></td>
			</tr>
		{% else %}
			<tr>
				<td colspan="4">Нет преподавателей</td>
			</tr>
		{% endfor %}
	</table>
</div>

src/AppBundle/Resources/views/teacherListPage.html.twig
{% extends "base.html.twig" %}
{% block header_content %}
	{{ macros.page_header("", "") }}
{% endblock %}
{% block javascripts %}
	<script src="{{ asset("bundles/app/js/teacherList.js") }}"></script>
{% endblock %}

{% block admin_lte_breadcrumb %}

	<div class="row">

		<div class="col-sm-12">
			<div class="box box-primary teacherListBox">
				<div class="box-header with-border">
					<h3 class="box-title">Список преподавателей</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container">
					<div class="box-body">

					</div>
					<div class="box-footer">

					</div>
				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

src/AppBundle/Resources/views/userList.html.twig
<table class="table table-bordered table-striped">
    <tr>
        <th>Номер</th>
        <th>Фамилия</th>
        <th>Имя</th>
        <th>Расписание</th>
    </tr>
    {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.first }}</td>
            <td>{{ user.last }}</td>
            <td><input type="button" class="btn btn-primary apply-sched" data-id="{{ user.id }}" value="Применить"></td>
        </tr>
    {% else %}
        <tr>
            <td colspan="10">
                Нет поделившихся учащихся
            </td>
        </tr>
    {% endfor %}
</table>

src/AppBundle/Resources/views/userListPage.html.twig
{% extends "base.html.twig" %}
{% block header_content %}
    {{ macros.page_header("", "") }}
{% endblock %}
{% block javascripts %}
    <script src="{{ asset("bundles/app/js/userList.js") }}"></script>
{% endblock %}

{% block admin_lte_breadcrumb %}

    <div class="row">

        <div class="col-sm-5">
            <div class="box box-primary userStatusBox">
                <div class="box-header with-border">
                    <h3 class="box-title">Статус</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <div class="form-container">
                    <div class="box-body">

                    </div>
                    <div class="box-footer">

                    </div>
                </div>
                <div class="overlay">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>
        </div>

        <div class="col-sm-7">
            <div class="box box-primary userListBox">
                <div class="box-header with-border">
                    <h3 class="box-title">Список поделившихся студентов</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <div class="form-container">
                    <div class="box-body">

                    </div>
                    <div class="box-footer">

                    </div>
                </div>
                <div class="overlay">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/userStatus.html.twig
<div class="row margin-bottom">
    <div class="col-sm-6">Текущий статус расписания</div>
    <div class="col-sm-6">
        {% if user.shareSched %}
            <span class="text-success">
            <strong>Поделился</strong>
        </span>
        {% else %}
            <span class="text-danger">
            <strong> Не делился</strong>
        </span>
        {% endif %}
    </div>
</div>
<div class="row text-center">
    {% if user.shareSched %}
        <input type="button" class="btn btn-danger share-btn" value="Отменить">
    {% else %}
        <input type="button" class="btn btn-success share-btn" value="Поделиться">
    {% endif %}
</div>