src/AppBundle/Entity/Expenditure.php
<?php

namespace AppBundle\Entity;

use CalendarBundle\Component\MonthConstant;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo; // gedmo annotations
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Expenditure
 *
 * @ORM\Table(name="expenditure")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ExpenditureRepository")
 */
class Expenditure
{

    const TYPE_NECESSARY = 0;
    const TYPE_DESIRED   = 1;
    const TYPE_OPTIONAL  = 2;
    const TYPE_UNPLANNED = 3;

    public static $types = [
        self::TYPE_NECESSARY => "Обязательные",
        self::TYPE_DESIRED   => "Желательные",
        self::TYPE_OPTIONAL  => "Необязательные",
        self::TYPE_UNPLANNED => "Внеплановые",
    ];

    /**
     * @var int
     *
     * @ORM\Column(name="Exp_Id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="Exp_Name", type="string", length=60)
     */
    private $name;

    /**
     * @var float
     * @ORM\Column(name="Exp_Sum", type="float")
     * @Assert\Range(min="0", max="1000000")
     */
    private $sum;

    /**
     * @var int
     * @ORM\Column(name="Exp_Type", type="integer")
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(name="Exp_Description", type="text")
     */
    private $description;

    /**
     * @var int
     * @ORM\Column(name="Exp_Month", type="integer")
     */
    private $month;

    /**
     * @var bool
     * @ORM\Column(name="Exp_Closed", type="boolean", options={"default": 0})
     */
    private $closed = 0;

    /**
     * @var int
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="id")
     * @ORM\JoinColumn(name="Exp_Student_Id")
     */
    private $user;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="Exp_Date_Added", type="datetime")
     */
    private $dateAdded;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Expenditure
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Expenditure
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set month
     *
     * @param integer $month
     *
     * @return Expenditure
     */
    public function setMonth($month)
    {
        $this->month = $month;

        return $this;
    }

    /**
     * Get month
     *
     * @return integer
     */
    public function getMonth()
    {
        return $this->month;
    }

    /**
     * @return mixed
     */
    public function getMonthName()
    {
        return MonthConstant::$month[$this->getMonth()];
    }

    /**
     * Set dateAdded
     *
     * @param \DateTime $dateAdded
     *
     * @return Expenditure
     */
    public function setDateAdded($dateAdded)
    {
        $this->dateAdded = $dateAdded;

        return $this;
    }

    /**
     * Get dateAdded
     *
     * @return \DateTime
     */
    public function getDateAdded()
    {
        return $this->dateAdded;
    }

    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return Expenditure
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set type
     *
     * @param integer $type
     *
     * @return Expenditure
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @return mixed
     */
    public function getTypeName()
    {
        return self::$types[$this->getType()];
    }

    /**
     * Set sum
     *
     * @param float $sum
     *
     * @return Expenditure
     */
    public function setSum($sum)
    {
        $this->sum = $sum;

        return $this;
    }

    /**
     * Get sum
     *
     * @return float
     */
    public function getSum()
    {
        return $this->sum;
    }

    /**
     * Set closed
     *
     * @param boolean $closed
     *
     * @return Expenditure
     */
    public function setClosed($closed)
    {
        $this->closed = $closed;

        return $this;
    }

    /**
     * Get closed
     *
     * @return boolean
     */
    public function getClosed()
    {
        return $this->closed;
    }
}

src/AppBundle/Form/ExpenditureType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Expenditure;
use CalendarBundle\Component\MonthConstant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class ExpenditureType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $numOfMonth = new \DateTime();

        $numOfMonthValue = (int)$numOfMonth->format("m");
        $builder
            ->add('name', null, [
                "label" => "Название"
            ])
            ->add('sum', null, [
                "label" => "Сумма"
            ])
            ->add('type', ChoiceType::class, [
                "choices" => Expenditure::$types,
                "label"   => "Тип"
            ])
            ->add('description', TextareaType::class, [
                "label" => "Описание"
            ])
            ->add('month', ChoiceType::class, [
                "choices" => MonthConstant::$month,
                "data"    => $numOfMonthValue,
                "label"   => "Месяц"
            ])
            ->add("save", SubmitType::class, [
                "label" => "Добавить",
                "attr" => [
                    "class" => "btn btn-danger pull-right"
                ]
            ]);
    }

    /**
     * {@inheritdoc}
     * @throws \Symfony\Component\OptionsResolver\Exception\AccessException
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Expenditure::class
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_expenditure';
    }


}

src/AppBundle/Controller/ExpenditureController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Component\Response\FormAcceptedResponse;
use AppBundle\Entity\Expenditure;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * Expenditure controller.
 *
 * @Route("expenditure")
 * @Security("has_role('ROLE_ADMIN', 'ROLE_USER')")
 */
class ExpenditureController extends Controller
{
    /**
     * Lists all expenditure entities.
     *
     * @Route("/list", name="expenditure_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $expenditures = $em->getRepository('AppBundle:Expenditure')->findBy([
            "user" => $this->getUser(),
        ]);

        return $this->render('@App/expenditure/index.html.twig', array(
            'expenditures' => $expenditures,
        ));
    }

    /**
     * Lists all expenditure entities.
     *
     * @Route("/monthList/{month}", name="expenditure_month_list")
     * @Method("GET")
     */
    public function monthListAction($month)
    {
        $em = $this->getDoctrine()->getManager();

        $expenditures = $em->getRepository('AppBundle:Expenditure')->findBy([
            "user" => $this->getUser(),
            "month" => $month
        ]);

        return $this->render('@App/expenditure/month.html.twig', array(
            'expenditures' => $expenditures,
        ));
    }

    /**
     * @param Expenditure|null $exp
     * @Route("/page", name="expend_page")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function pageAction(Expenditure $exp = null)
    {
        return $this->render("@App/expenditure/page.html.twig", [
            "id" => is_null($exp) ? null : $exp->getId()
        ]);
    }

    /**
     * Creates a new expenditure entity.
     *
     * @Route("/new", name="expenditure_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $expenditure = new Expenditure();
        $form = $this->createForm('AppBundle\Form\ExpenditureType', $expenditure, [
            "action" => $this->generateUrl("expenditure_new")
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($expenditure);
            $em->flush();

            return new FormAcceptedResponse();
        }

        return $this->render('@App/expenditure/new.html.twig', array(
            'expenditure' => $expenditure,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a expenditure entity.
     *
     * @Route("/{id}", name="expenditure_show")
     * @Method("GET")
     */
    public function showAction(Expenditure $expenditure)
    {
        $deleteForm = $this->createDeleteForm($expenditure);

        return $this->render('expenditure/show.html.twig', array(
            'expenditure' => $expenditure,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing expenditure entity.
     *
     * @Route("/{id}/edit", name="expenditure_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Expenditure $expenditure)
    {
        $deleteForm = $this->createDeleteForm($expenditure);
        $editForm = $this->createForm('AppBundle\Form\ExpenditureType', $expenditure);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('expenditure_edit', array('id' => $expenditure->getId()));
        }

        return $this->render('expenditure/edit.html.twig', array(
            'expenditure' => $expenditure,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a expenditure entity.
     *
     * @Route("/remove/{id}", name="expenditure_delete")
     * @param Expenditure $expenditure
     * @return FormAcceptedResponse
     * @throws \LogicException
     */
    public function deleteAction(Expenditure $expenditure)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($expenditure);
        $em->flush();

        return new FormAcceptedResponse();
    }

    /**
     * Creates a form to delete a expenditure entity.
     *
     * @param Expenditure $expenditure The expenditure entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Expenditure $expenditure)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('expenditure_delete', array('id' => $expenditure->getId())))
            ->setMethod('DELETE')
            ->getForm();
    }

    /**
     * @param Expenditure $expenditure
     * @param $val
     * @return FormAcceptedResponse
     * @Route("/closed/{id}/{val}", name="expenditure_closed_update")
     */
    public function updateClosedValueAction(Expenditure $expenditure, $val)
    {
        $val = $val === 'true' ? true : false;
        $expenditure->setClosed($val);
        $this->getDoctrine()->getManager()->flush();

        return new FormAcceptedResponse();

    }
}

src/AppBundle/Resources/views/expenditure/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Expenditure edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" />
    {{ form_end(edit_form) }}

    <ul>
        <li>
            <a href="{{ path('expenditure_index') }}">Back to the list</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock %}

src/AppBundle/Resources/views/expenditure/index.html.twig
<div class="table-responsive">
<table class="table table-bordered table-striped">
	<thead>
	<tr>
		<th>Номер</th>
		<th>Название</th>
		<th>Сумма</th>
		<th>Тип</th>
		<th>Описание</th>
		<th>Месяц</th>
		<th>Дата добавления</th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	{% for expenditure in expenditures %}
		<tr>
			<td>{{ expenditure.id }}</td>
			<td>{{ expenditure.name }}</td>
			<td>{{ expenditure.sum }}</td>
			<td>{{ expenditure.typeName }}</td>
			<td>{{ expenditure.description }}</td>
			<td>{{ expenditure.monthName }}</td>
			<td>{% if expenditure.dateAdded %}{{ expenditure.dateAdded|date('Y-m-d H:i:s') }}{% endif %}</td>
			<td><i class="fa fa-remove text-danger exp-remove" data-id="{{ expenditure.id }}"></i></td>
		</tr>
	{% else %}
		<tr class="text-center">
			<td colspan="7">Нет записей</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
</div>

src/AppBundle/Resources/views/expenditure/month.html.twig
<script type="text/javascript">
	//	$(function () {
	//		$('input').iCheck({
	//			checkboxClass: 'icheckbox_square-blue',
	//			radioClass: 'iradio_square-blue',
	//			increaseArea: '20%' // optional
	//		});
	//	});

</script>
<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
		<tr>
			<th>Название</th>
			<th>Сумма</th>
			<th>Тип</th>
			<th>Описание</th>
			<th>Месяц</th>
			<th>Дата добавления</th>
			<th>Оплатить</th>
			<th>Удалить</th>
		</tr>
		</thead>
		<tbody>
		{% for expenditure in expenditures %}
			<tr {% if expenditure.closed %} class="bg-info text-white" {% endif %}>
				<td>{{ expenditure.name }}</td>
				<td>{{ expenditure.sum }}</td>
				<td>{{ expenditure.typeName }}</td>
				<td>{{ expenditure.description }}</td>
				<td>{{ expenditure.monthName }}</td>
				<td>{% if expenditure.dateAdded %}{{ expenditure.dateAdded|date('Y-m-d H:i:s') }}{% endif %}</td>
				<td>
					<input type="checkbox" class="custom-checkbox paid" {% if expenditure.closed %} checked {% endif %}
						   data-id="{{ expenditure.id }}" value="on">
				</td>
				<td><i class="fa fa-remove text-danger exp-remove" data-id="{{ expenditure.id }}"></i></td>
			</tr>
		{% else %}
			<tr class="text-center">
				<td colspan="7">Нет записей</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
</div>

src/AppBundle/Resources/views/expenditure/new.html.twig
{{ form_start(form) }}
<div class="box-body">
    {{ form_row(form.name) }}
    {{ form_row(form.type) }}
    {{ form_row(form.sum) }}
    {{ form_row(form.description) }}
    {{ form_row(form.month) }}
</div>
<div class="box-footer">
    {{ form_row(form.save) }}
</div>
{{ form_end(form) }}

src/AppBundle/Resources/views/expenditure/page.html.twig
{% extends "base.html.twig" %}

{% block header_content %}
	{{ macros.page_header("Расходы", "") }}
{% endblock %}

{% block javascripts %}
	<script src="{{ asset("bundles/app/js/expenditure.js") }}"></script>
{% endblock %}

{% block admin_lte_breadcrumb %}
	{% if id is defined %}
		<div id="budget_id" data-id="{{ id }}"></div>
	{% endif %}
	<div class="row">
		<div class="col-sm-4">
			<div class="box box-primary expFormBox">
				<div class="box-header with-border">
					<h3 class="box-title">Расходы</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="form-container"></div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>

		<div class="col-sm-8">
			<div class="box box-primary expListBox">
				<div class="box-header with-border">
					<h3 class="box-title">Информация по месяцам</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div><!-- /.box-tools -->
				</div>
				<div class="box-body">
				</div>
				<div class="overlay">
					<i class="fa fa-refresh fa-spin"></i>
				</div>
			</div>
		</div>

	</div>


{% endblock %}

src/AppBundle/Resources/views/expenditure/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Expenditure</h1>

    <table>
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ expenditure.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ expenditure.name }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ expenditure.type }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ expenditure.description }}</td>
            </tr>
            <tr>
                <th>Month</th>
                <td>{{ expenditure.month }}</td>
            </tr>
            <tr>
                <th>Dateadded</th>
                <td>{% if expenditure.dateAdded %}{{ expenditure.dateAdded|date('Y-m-d H:i:s') }}{% endif %}</td>
            </tr>
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('expenditure_index') }}">Back to the list</a>
        </li>
        <li>
            <a href="{{ path('expenditure_edit', { 'id': expenditure.id }) }}">Edit</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock %}